#画像のパラメータ
image:
  resize_size: 256
  crop_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

#モデルのパラメータ
train:
  caption_path: './data/annotations/captions_train2014.json'
  vocab_threshold: 5
  vocab_from_file: True
  encoder_path: './models/encoder-5-3000.pkl'
  decoder_path: './models/encoder-5-3000.pkl'
  vocab_path: './data/vocab.pkl'
  threshold: 4

  # for train.py
  model_path: './models/'
  crop_size: 224
  log_step: 10
  save_step: 1000

  # model parameters
  embed_size: 256
  hidden_size: 512
  num_layers: 1
  num_epochs: 5
  batch_size: 128
  num_workers: 2
  learning_rate: 0.001







# resize.pyのパラメータ
resize:
  image_dir: './data/train2014/'
  output_dir: './data/resized2014/'
  image_size: 256

sample:
  # sampleを動かす際の画像のパス
  image_path: './data/sample_pic01.jpg'



#最適化手法のパラメータ
optimizer:
  algorithm: momentum_SDG
  lr: 0.001
  momentum: 0.9