#画像のパラメータ
image:
  resize_size: 256
  crop_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

#モデルのパラメータ
train:
  embed_size: 256
  batch_size: 512
  vocab_threshold: 5
  vocab_from_file: True
  hidden_size: 512
  encoder_path: 'models/encoder-5-3000.pkl'
  decoder_path: 'models/encoder-5-3000.pkl'
  vocab_path: 'data/vocab.pkl'
  num_layers: 1

# resize.pyのパラメータ
resize:
  image_dir: './data/train2014/'
  output_dir: './data/resized2014/'
  image_size: 256




#最適化手法のパラメータ
optimizer:
  algorithm: momentum_SDG
  lr: 0.001
  momentum: 0.9