#画像のパラメータ
image:
  resize_size: 256
  crop_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  batch_size: 32

#モデルのパラメータ
train:
  num_epochs: 20

#最適化手法のパラメータ
optimizer:
  algorithm: momentum_SDG
  lr: 0.001
  momentum: 0.9